on: 
  push:
    branches: 
    - master
name: Production Deploy
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v2
    
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.2.0
      with:
        server: files.000webhost.com
        server-dir: ./public_html/
        username: s-i-a-f
        password: ${{ secrets.ftp_password }}
